# Jekyll configuration
markdown: kramdown
highlighter: rouge
# paginate: 10
language : 'ko-KR'

url: "https://softbowllab.github.io/"
baseurl: "/sbux"


# Website info
title: SBUx
subtitle: SBUx 2.6 Technical Training Site 
email: a10j22s@softbowl.co.kr
description: Technical Training Site

# cover : img/bg.jpg
# blog home에 표시될 blog cover image.
favicon: img/favicon.ico


# Social info
navigation: True
# Navigation bar link를 보여줄건지 여부

# twitter :
# twitter_username: softbowl
github_username:  softbowllab 

# Disqus
disqus: True
disqus_shortname: "softbowllab"
# disqus는 온라인 댓글 시스템. 댓글 기능을 사용하기 위해
# disqus를 이용할 것인지 여부와 만약 사용하면
# disqus shortname을 입력 ( disqus username이 아님 )

# 변수
codeurl: 'https://github.com/softbowllab/sbux'

# gems and other configs
# plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
plugins: [jekyll-sitemap]
exclude: ['Gemfile', 'Gemfile.lock', .gitignore','README.md']
#feed:
#   path: feed.xml

branch : gh-pages

collections:
  docs:
    output: true
  examples:
    output: true

defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    permalink: /:collection/release/:path:output_ext
- scope:
    path: _examples
    type: examples
  values:
    layout: examples
    permalink: /:collection/release/:categories/:name:output_ext
- scope:
    path: "_examples/latest/assets"
  values:
    permalink: release/:path:output_ext

# 변수 (release 카테고리)
release:
  latest: 
    - {name: "common"}
    - {name: "input"}
    - {name: "picker"}

tutorial:
  - {name: ""}

# favicon: /assets/favicon.ico
# feed:
#   path: atom.xml
# css: assets/css
# js: assets/js
# images: assets/images
